### ISSUE TITLE
[BUG] can't punch on windows mixed reality

### ISSUE THREAD

**Issue by golubxd** [whateverusername0/VRTRAKILL#66] opened 2023-06-28 09:25 UTC
can't punch on windows mixed reality. worst of all - punching isn't even binded by default! i had to make my own bind for punching and after all i couldn't punch - it worked with huge delay, and i can't bind it on the trigger.

just make it on the left trigger by default

i would expect that punching would be on the left trigger by default, but jumping was binded for the left trigger

 headset: [HP Windows Mixed Reality]
 version 0.11.2

**Comment by whateverusername0** [comment] 2023-06-28 09:31
I wasn't doing those bindings, because i don't have the controllers to try it out for convenience, so it's not my problem, lolol 😇
Also the way punching works is that whenever it detects high controller speed it instantly does it's thing, and if i remove the "default punching animation", which acts as the only cooldown, things will break. So yea i can't help you w/ the huge delay thing, sorry

**Comment by whateverusername0** [comment] 2023-06-28 09:47
🥺

**Comment by pararara1** [comment] 2023-07-01 17:48
When i press the punch button(i bound it myself) and do a swing i see a punch animation start and then my game crashes
[Player.log](https://github.com/whateverusername0/VRTRAKILL/files/11926794/Player.log)

**Comment by whateverusername0** [comment] 2023-07-02 05:51
damn. logs tell me absolutely nothing. can you send a video or smh of yo u doing the punch? perhaps i could see something weird there

**Comment by pararara1** [comment] 2023-07-02 15:32
Oh it works and doesnt crash when i disable velocity.

**Comment by whateverusername0** [comment] 2023-07-04 07:06
cool. i'll have a look on that

**Comment by Tachrayonic** [comment] 2023-07-13 13:57
First time starting this up with Index Controllers, by default I needed to both press the keybind and swing my hand to trigger a punch.
Punching with my hand alone did nothing, and pressing the keybind alone did nothing.

**Comment by whateverusername0** [comment] 2023-07-15 15:31
can't reproduce. srry, ig i won't fix that (because i can't)

**Closed by whateverusername0** 2023-07-15 15:31 UTC
Labels: bug
