### ISSUE TITLE
[Feature Request] Support for OVR through Virtual Desktop

### ISSUE THREAD

**Issue by carrotfarm02** [whateverusername0/VRTRAKILL#82] opened 2023-08-03 23:13 UTC
It would be nice to have Oculus (or i guess Meta) support when using virtual desktop, because currently I cannot play VRtrakill (there are no errors with it besides the controls not functioning.

**Comment by whateverusername0** [comment] 2023-08-04 01:55
I am unable to reproduce this issue, because I don't have virtual desktop (and I don't want to buy it); also I've seen other people play with virtual desktop as well, so I guess it should be a problem on your side. Can't do anything with that, sorry :(
But I guess you can try:
- Playing with oculus link or wired ALVR.
- Check your controller bindings.
Or try fixing the issue in the discord with other people who managed to get it working (small *chat* button).

**Comment by whateverusername0** [comment] 2023-08-04 08:02
forgot to close the issue

**Closed by whateverusername0** 2023-08-04 08:02 UTC
Labels: feature request

**Comment by carrotfarm02** [comment] 2023-08-04 13:47
My key binds were set wrong, this is not an issue at all anymore. (had them set to default)
