### ISSUE TITLE
Game no work.

### ISSUE THREAD

**Issue by DiamondYoshi** [whateverusername0/VRTRAKILL#24] opened 2023-05-06 01:04 UTC
**Describe the bug**
The game pretty much does not work.

**Steps to Reproduce**
1. Do the steps for installation before VR'ing my ultrakill
2. Install from the already done zip
3. Do the steps for doing the thing and whatever
4. Play game in VR
5. Oops, no gameplay functionality.

**Expected behavior**
Idk, game?

**Real behavior**
All GUIs lack being and I can't move

**Media**
# If applicable, add screenshots / videos to help explain your problem.
can't do as it's all in VR and PC gives the intended look and I can do things on PC.

**Other info:**
 - Headset: Oculus Quest 2
 - Software: Oculus App with Quest Link
 - VRTRAKILL Version: 0.8.2

**Additional context**
Windows 10
64 Bit
Used the zip (not source code)

**Comment by whateverusername0** [comment] 2023-05-06 01:50
did it start steamvr? have you actually installed bepinex? i can't reproduce the problem thus i cannot help you

**Comment by whateverusername0** [comment] 2023-05-06 07:51
also im leaving this issue open for 2 days and if you won't answer i'll be closing it

**Comment by Prodgidy** [comment] 2023-05-06 08:17
i think i had the same issue once but i just restarted and it fixed itself

**Comment by Mr-Foxtrot** [comment] 2023-05-06 20:06
> **Describe the bug** The game pretty much does not work.
> 
> **Steps to Reproduce**
> 
> 1. Do the steps for installation before VR'ing my ultrakill
> 2. Install from the already done zip
> 3. Do the steps for doing the thing and whatever
> 4. Play game in VR
> 5. Oops, no gameplay functionality.
> 
> **Expected behavior** Idk, game?
> 
> **Real behavior** All GUIs lack being and I can't move
> 
> **Media**
> 
> # If applicable, add screenshots / videos to help explain your problem.
> can't do as it's all in VR and PC gives the intended look and I can do things on PC.
> 
> **Other info:**
> 
> * Headset: Oculus Quest 2
> * Software: Oculus App with Quest Link
> * VRTRAKILL Version: 0.8.2
> 
> **Additional context** Windows 10 64 Bit Used the zip (not source code)

Some suggestions that might fix it:
- Usually if the game boots in VR but no GUI shows up (including the menu) this is because you don't have bepinex loading the mod, or much more likely bepinex isn't installed, the mod won't work without the bepinex loader nor does it come with bepinex.
- Once you boot the game once, you need to close it so the config is generated for the future. Also make sure the config uses the same keybinds as your ULTRAKILL keybinds. Once done restart the game and see how it goes.
- Disconnect any and all additional controllers, like xbox, playstation, joycons, etc. as they can cause major conflict from my testing. (Random inputs/no input, crazy fast weapon scrolling, etc.)
- Make sure you don't have any other mods enabled, as lately a majority of mods don't work due to the sharpshooter update, and a couple probs wouldn't work with VR.

**Comment by DiamondYoshi** [comment] 2023-05-08 11:29
> did it start steamvr? have you actually installed bepinex? i can't reproduce the problem thus i cannot help you

I had steamvr open and I could look around, I also installed bepinex

**Comment by JoetheKcha5attT** [comment] 2023-05-11 21:35
I'm having the exact same problem. I'm using the same headset too. I also have a 64 bit.

**Comment by JoetheKcha5attT** [comment] 2023-05-11 21:46
Fixed it by installing the  8.3.0 version of VRLTRAKILL. For some reason the latest one just doesn't load the Plugin properly. This might be due to the amount of files that aren't in the merged ULTRAKILL files. idk tho it's pretty buggy

**Closed** 2023-05-12 09:55 UTC
Labels: bug
