### ISSUE TITLE
[BUG] Arms won't move from the floor

### ISSUE THREAD

**Issue by Scruq445** [whateverusername0/VRTRAKILL#49] opened 2023-06-13 21:16 UTC
**Describe the bug**
When Entering a Level, both hands won't move from the floor even if controllers are connected and tracking.

**Other info:**
 - Headset: Lenovo Experience 
 - Intermediate software: Windows Mixed Reality
 - VRTRAKILL Version 0.10

**Comment by whateverusername0** [comment] 2023-06-14 01:15
uh what's a "lenovo experience"? i've never seen a headset with such a name.
also i don't think mixed reality works by default. do you have steamvr support installed? https://store.steampowered.com/app/719950/Windows_Mixed_Reality_for_SteamVR/
if you say "load into a level" that means you got past the menu. what about it? do the controllers get normally tracked there?
(really i don't know what to do :( you're the first person with mixed reality here)

**Comment by whateverusername0** [comment] 2023-06-16 03:13
Hello?

**Comment by Scruq445** [comment] 2023-06-18 04:42
>

**Comment by Scruq445** [comment] 2023-06-18 04:44
Yes, I have SteamVR support installed. When entering a level, I mean having gone past the main title and ellevel select and into the room, V1 dropped into.

**Comment by whateverusername0** [comment] 2023-06-19 10:17
I really don't know how to deal with mixed reality. I'll just leave the issue open until i find a way to help you out. Srry.

**Comment by Scruq445** [comment] 2023-06-19 21:29
I think it could be a binding problem, same thing happened when I removed the binding files when installing H3. Gonna create a file for it rq and see if it works.

**Comment by Scruq445** [comment] 2023-06-20 06:04
Made a keybind for the WMR controllers (also known as holographic controllers in Unity bindings). Only things it doesn't have is a Punch and Weapon Scroll button, which may cause an issue as with the latest release with the new punch mechanics, but I can't find any space on the controller other than using another trackpad button.

**WMR Controller Bindings:** (have to change file type to json.)
[export_steam_app_0_holographic_controller_VRTRAKILL Windows MR Controller Bindings.txt](https://github.com/whateverusername0/VRTRAKILL/files/11796432/export_steam_app_0_holographic_controller_VRTRAKILL.Windows.MR.Controller.Bindings.txt)

**WMR Controller Mapping:**
![video_image-gtkRIT-ms](https://github.com/whateverusername0/VRTRAKILL/assets/109207982/6e71dbab-5b2f-426b-a506-0d54368f27b9)

Hope this does well with other WMR Users.

**Comment by whateverusername0** [comment] 2023-06-20 13:09
cheerios, m8, i'm making them default now.
if the problem is fixed (by making a set of controller bindings for wmr) you can close the issue

**Comment by whateverusername0** [comment] 2023-06-26 03:59
yeah considering it was a bindings issue and it's *probably* now fixed i'm gonna close the issue, thx :)

**Closed** 2023-06-26 03:59 UTC
Labels: bug
