### ISSUE TITLE
Not able to get a score at the end of a level

### ISSUE THREAD

**Issue by MEGACHEB** [whateverusername0/VRTRAKILL#57] opened 2023-06-19 18:55 UTC
Whenever I beat a level in version 0.10, nothing pops up except for the amount of P I get, which is always zero. I also cannot enter into the next level, and I have to exit out of the level every time I want to move onto another level

**Steps to Reproduce**
1. beat a level
2. no P :(

**Expected behavior**
You get no rank for the level, but it counts as you beating it

**Real behavior**
idk

**Other info:**
 - Headset : Oculus Quest 2
 - Intermediate software : Oculus Air Link
 - VRTRAKILL Version : 0.10

**Comment by whateverusername0** [comment] 2023-06-19 18:59
i'll try to reproduce the bug on a new save and let you know. in the meantime could you please send a video of the bug? it'll really help.

also to proceed to the next level you need to press the right trigger (primary fire button by default), if you haven't known that.

**Comment by MEGACHEB** [comment] 2023-06-19 19:03
yeah I've mashed every button on my keyboard and controller and nothing happens, just me, the p, and the elevator

**Comment by MEGACHEB** [comment] 2023-06-19 19:04
![image](https://github.com/whateverusername0/VRTRAKILL/assets/100053782/e5a19f14-ab77-4d51-b2ab-6aa3b268a85d)

**Comment by whateverusername0** [comment] 2023-06-21 05:30
i can't reproduce the bug. everything *just works*. i really don't know what's happening here. i guess i'll just leave it open until i figure out what to do with it.

**Comment by MEGACHEB** [comment] 2023-06-21 21:16
I could try disabling all my mods, idk why my dumbass didn't think of that before

**Comment by whateverusername0** [comment] 2023-06-26 04:00
so uh.. did disabling other mods work?

**Comment by whateverusername0** [comment] 2023-06-28 09:38
i'm gonna close it for imaginary statistics and eye pleasure, ty for understanding :)

**Closed by whateverusername0** 2023-06-28 09:38 UTC
Labels: bug, can't fix
