### ISSUE TITLE
[BUG] Dash leaves much to be desired, slide and bunnyhop abysmal when moving

### ISSUE THREAD

**Issue by Icykitsune** [whateverusername0/VRTRAKILL#80] opened 2023-07-27 04:18 UTC
Before reporting anything, see [Common problems](https://github.com/whateverusername0/VRTRAKILL#common-issues)  
Also expect meanie things to be said (https://github.com/whateverusername0/VRTRAKILL/issues/48) (lol)

**Describe the bug**
Exactly what the title says; whenever I am holding any direction, dashes go half the normal distance they normally would, slides have little speed, and a bunnyhop will become unsexy

**Steps to Reproduce**
1. Hold the movement stick in any direction
2. Either dash, slide, or slide jump
3. Ultrasad

**Expected behavior**
Launches at Ultraspeed and dashes of the Ultrakill variety

**Real behavior**
Sad, whimpy V1, with too much friction to move correctly

**Media**
https://1drv.ms/f/s!AoEdj-TQFmM6-lP-c06q83-JCL9l?e=dZ0OyO

**Other info:**
 - Headset: Oculus Quest 2
 - Intermediate software: Oculus Link
 - VRTRAKILL Version 0.11.2

**Additional context**
If I recall correctly, This wasn't happening a few weeks ago, and I don't believe I have changed anything in the config that's worth talking about. I have no other mods, and my refresh rate is set to 72(default). I would like to not update until 0.12 is not in preview. But if it is fixed in the 0.12 preview, I will.

**Comment by Icykitsune** [comment] 2023-07-27 04:25
Also, as shown in the video, moving slowly will negate all speed changes from the dash and slide. If this takes time to fix, Then I'll be patient. I'm a fun little guy. However if this is something on my end, feel free to list all of the ways I'm a dumbass

**Comment by whateverusername0** [comment] 2023-07-27 04:33
Just saying that i did not do *any* drastic changes in the way player movement behaves.
So i think the problem is in how the *base game* behaves. Probably when dash/slide/etc. doesn't get any initial speed it adds it's own, and when it has it doesn't. I'll check on it.
Also in 0.12p1 there's no movement changes.

**Comment by whateverusername0** [comment] 2023-08-22 08:16
should be fixed in the next minor update

**Closed by whateverusername0** 2023-08-22 08:16 UTC
Labels: bug
