### ISSUE TITLE
[BUG] Left Hand mode doesn't do anything

### ISSUE THREAD

**Issue by thatonep** [whateverusername0/VRTRAKILL#56] opened 2023-06-16 02:03 UTC
It might just not be implemented yet but I'm left handed and the left handed mode swaps where the crosshair is but not which hand the gun is in. I made sure it was active in the config file and all it did was switch the crosshair hand. Because there is a crosshair, I can still aim even with my non-dominant hand, although a left handed mode would be nice to implement when it's working

**Comment by whateverusername0** [comment] 2023-06-16 02:59
it's not a bug. it's still not implemented yet. i even marked it as "(unused)". i'm working on it. will be coming in 0.10.x

**Closed** 2023-06-16 02:59 UTC
Labels: bug
