### ISSUE TITLE
disabling controller haptics screws everything up

### ISSUE THREAD

**Issue by afsfafafafafaf** [whateverusername0/VRTRAKILL#40] opened 2023-06-07 21:00 UTC
**Describe the bug**
If you disable controller haptics in the config your hands get glued to your face and you can't shoot

**Steps to Reproduce**
1. Disable haptics in config
2. Open the game
3. suffer

**Expected behavior**
Playing normally without haptics

**Real behavior**
Hands got stuck in my head ouch

**Media**
![image](https://github.com/whateverusername0/VRTRAKILL/assets/45293838/60590bd9-1788-4eb6-8c36-1fcb69447c7f)

**Other info:**
 - Happened on Oculus quest 2
 - Used quest link
 - Version 0.9

**Additional context**
it sucks

**Comment by whateverusername0** [comment] 2023-06-08 02:13
i'm playing without controller haptics myself and.. everything works?? i'm gonna need your entire config for that

**Comment by whateverusername0** [comment] 2023-06-09 08:22
i can't reproduce the bug. i need more details (logs + config).

**Comment by whateverusername0** [comment] 2023-06-11 17:13
i think it's an performance issue. let's just say "a *special case*", so i'm not soncidering it an issue and it might be fixed in 0.10, yeah ok closing the issue now

**Closed by whateverusername0** 2023-06-11 17:13 UTC
Labels: bug
